# Camera
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
TARGET_PROVIDES_CAMERA_HAL := true
TARGET_NEEDS_METADATA_CAMERA_SOURCE := true
USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_USES_MEDIA_EXTENSIONS := true
BOARD_GLOBAL_CFLAGS += -DMETADATA_CAMERA_SOURCE
